name: Cargo

on:
  workflow_dispatch:
    

permissions: read-all

jobs:
  cargo:
    runs-on: ubuntu-latest
    name: Cargo
    steps:
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1 -Tls openssl -ForBuild
      shell: pwsh
    - name: Install Cargo
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Cargo build
      run: cargo build --all
    - name: Cargo test
      run: cargo test --all -v

