name: Plugins

on:
  push:
    branches:
    - main
    paths:
      - .github/workflows/plugins.yml
      - src/plugins
  pull_request:
    branches:
    - main
    paths:
      - .github/workflows/plugins.yml
      - src/plugins

permissions: read-all

jobs:
  build_dbgext:
    name: Build WinDbg Extension
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]
        platform: [x86, x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@9546707e6b8f513d3a2af998e51e3b995c9fbe81
    - name: Build
      run: msbuild src\plugins\msquic.windbg.sln /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}
    # TODO - Upload artifacts

  build_quictrace:
    name: Build QuicTrace
    needs: []
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]
    steps:
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
    - name: Setup .NET
      uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build src\plugins\QuicTrace.sln -c ${{ matrix.configuration }}
    # TODO - Upload artifacts

